% Wavelet Toolbox Demo Section
% Version 3.0  1-Jun-96
%
% Wavelet Toolbox Demo programs.
%    genimg    	- Generation of a set of 11 different test images 
%    wtdemo    	- Menu for all the available demos 
%    wt___dmo  	- Demo on some 1D wavelet transform capabilities 
%    wt2d_dmo  	- Menu for 2D wavelet transform demos
%    wvt2ddmo	- Demo on some 2D wavelet capabilities
%    fmt2ddmo	- Demo on the output format for 2D wavelet transform
%    mrs__dmo  	- Demo on 1D / 2D multiresolution analysis
%    flds_dmo	- Menu for filter design demos
%    flt_dmo.m  - Submenu for the available filter families
%    daub_dmo	- Demo on orthogonal Daubechies' filters generation
%    wspl_dmo	- Demo on biorthogonal spline wavelets
%    syml_dmo	- Demo on 'Symlet' filters
%    flat_dmo	- Demo on maximally flat wavelet filters
%    btlmrdmo	- Demo on Battle-Lemarie filters
%    remezdmo	- Demo on Remez wavelet filters
%    reg__dmo   - Demo on regularity estimates
%    scaldmo    - Demo of the scalogram 
%    wpkdmo     - Menu for 1D wavelet packet transform demos
%    formatdm   - Demo on the formats of the wavelet packet basis
%    wp_dmo     - Demo on some 1D wavelet packet transform capabilities 
%    basisdmo   - Demo on 1D tree search algorithms
%    wpk2ddmo	- Menu for 2D wavelet packet transform demos
%    wp2d_dmo	- Demo on some 2D WP transform capabilities 
%    bas2ddmo	- Demo on Coifman-Wickerhauser basis selection algorithm for 2D
%    gnimgdmo  	- Shows images generated by genimg 
%
% Data.
%    lena	- Greyscale image of Lena
%    lena2	- Fragment of Lena image
%    kitten	- Grayscale Kitty image 
%    filt3	- Biorthogonal filter set for demos 
%    filtd8	- Orthogonal filter set for demos 
%    filtd16    - Orthogonal filter set for demos 
%    basis      - Example of basis format for the 1-D WP transform
%    basis2d    - Example of basis format for the 2-D WP transform
%    speech1	- Speech signal example 
%    speech2	- Speech signal example 
%    zappa      - Audio signal example 
%    zappa2     - Audio signal example  
%
%   Copyright 1996, Universidad de Vigo
%   All rights reserved.
